carUrl: http://car-policy-service:8080

homeUrl: http://home-policy-service:8080

customerUrl: http://customer-service:8080

opentracing:
  headers:
    - x-request-id
    - x-b3-traceid
    - x-b3-spanid
    - x-b3-parentspanid
    - x-b3-sampled
    - x-b3-flags
    - x-ot-span-context

logging:
  level:
    com.codependent: debug
    org.springframework.web: debug
