  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: customer-rating-service
    labels:
      app: customer-rating-service
      version: v1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: customer-rating-service
        version: v1
    template:
      metadata:
        labels:
          app: customer-rating-service
          version: v1
      spec:
        containers:
          - name: customer-rating-service
            image: prfl/customer-rating-service:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-rating-service
  labels:
    app: customer-rating-service
    service: customer-rating-service
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: customer-rating-service
