apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: insuranceinc
  namespace: istio-insuranceinc
spec:
  hosts:
  - "*"
  gateways:
  - insuranceinc-gateway
  http:
  - match:
    - uri:
        prefix: /insuranceinc
    rewrite:
      uri: " "
    route:
    - destination:
        host: global-position-service
        port:
          number: 8080
---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: car-policy-service
#spec:
#  hosts:
#  - car-policy-service
#  http:
#  - route:
#    - destination:
#        host: car-policy-service
#        subset: v1