apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customer-service-destination-rule
  namespace: istio-insuranceinc
spec:
  host: customer-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customer-rating-service
  namespace: istio-insuranceinc
spec:
  host: customer-rating-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1